use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
pub struct Boards {
    pub boards: Vec<Board>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Board {
    pub board: String,
    pub title: String,
    #[serde(rename = "ws_board")]
    pub ws_board: i64,
    #[serde(rename = "per_page")]
    pub per_page: i64,
    pub pages: i64,
    #[serde(rename = "max_filesize")]
    pub max_filesize: i64,
    #[serde(rename = "max_webm_filesize")]
    pub max_webm_filesize: i64,
    #[serde(rename = "max_comment_chars")]
    pub max_comment_chars: i64,
    #[serde(rename = "max_webm_duration")]
    pub max_webm_duration: i64,
    #[serde(rename = "bump_limit")]
    pub bump_limit: i64,
    #[serde(rename = "image_limit")]
    pub image_limit: i64,
    pub cooldowns: Cooldowns,
    #[serde(rename = "meta_description")]
    pub meta_description: String,
    #[serde(rename = "is_archived")]
    pub is_archived: Option<i64>,
    pub spoilers: Option<i64>,
    #[serde(rename = "custom_spoilers")]
    pub custom_spoilers: Option<i64>,
    #[serde(rename = "forced_anon")]
    pub forced_anon: Option<i64>,
    #[serde(rename = "user_ids")]
    pub user_ids: Option<i64>,
    #[serde(rename = "country_flags")]
    pub country_flags: Option<i64>,
    #[serde(rename = "code_tags")]
    pub code_tags: Option<i64>,
    #[serde(rename = "webm_audio")]
    pub webm_audio: Option<i64>,
    #[serde(rename = "min_image_width")]
    pub min_image_width: Option<i64>,
    #[serde(rename = "min_image_height")]
    pub min_image_height: Option<i64>,
    pub oekaki: Option<i64>,
    #[serde(rename = "sjis_tags")]
    pub sjis_tags: Option<i64>,
    #[serde(rename = "board_flags")]
    pub board_flags: Option<BoardFlags>,
    #[serde(rename = "text_only")]
    pub text_only: Option<i64>,
    #[serde(rename = "require_subject")]
    pub require_subject: Option<i64>,
    #[serde(rename = "math_tags")]
    pub math_tags: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Cooldowns {
    pub threads: i64,
    pub replies: i64,
    pub images: i64,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct BoardFlags {
    #[serde(rename = "AC")]
    pub ac: Option<String>,
    #[serde(rename = "AN")]
    pub an: Option<String>,
    #[serde(rename = "BL")]
    pub bl: Option<String>,
    #[serde(rename = "CF")]
    pub cf: Option<String>,
    #[serde(rename = "CM")]
    pub cm: Option<String>,
    #[serde(rename = "CT")]
    pub ct: Option<String>,
    #[serde(rename = "DM")]
    pub dm: Option<String>,
    #[serde(rename = "EU")]
    pub eu: Option<String>,
    #[serde(rename = "FC")]
    pub fc: Option<String>,
    #[serde(rename = "GN")]
    pub gn: Option<String>,
    #[serde(rename = "GY")]
    pub gy: Option<String>,
    #[serde(rename = "JH")]
    pub jh: Option<String>,
    #[serde(rename = "KN")]
    pub kn: Option<String>,
    #[serde(rename = "MF")]
    pub mf: Option<String>,
    #[serde(rename = "NB")]
    pub nb: Option<String>,
    #[serde(rename = "NZ")]
    pub nz: Option<String>,
    #[serde(rename = "PC")]
    pub pc: Option<String>,
    #[serde(rename = "PR")]
    pub pr: Option<String>,
    #[serde(rename = "RE")]
    pub re: Option<String>,
    #[serde(rename = "TM")]
    pub tm: Option<String>,
    #[serde(rename = "TR")]
    pub tr: Option<String>,
    #[serde(rename = "UN")]
    pub un: Option<String>,
    #[serde(rename = "WP")]
    pub wp: Option<String>,
    #[serde(rename = "4CC")]
    pub n4_cc: Option<String>,
    #[serde(rename = "ADA")]
    pub ada: Option<String>,
    #[serde(rename = "ANF")]
    pub anf: Option<String>,
    #[serde(rename = "APB")]
    pub apb: Option<String>,
    #[serde(rename = "AJ")]
    pub aj: Option<String>,
    #[serde(rename = "AB")]
    pub ab: Option<String>,
    #[serde(rename = "AU")]
    pub au: Option<String>,
    #[serde(rename = "BB")]
    pub bb: Option<String>,
    #[serde(rename = "BM")]
    pub bm: Option<String>,
    #[serde(rename = "BP")]
    pub bp: Option<String>,
    #[serde(rename = "BS")]
    pub bs: Option<String>,
    #[serde(rename = "CL")]
    pub cl: Option<String>,
    #[serde(rename = "CO")]
    pub co: Option<String>,
    #[serde(rename = "CG")]
    pub cg: Option<String>,
    #[serde(rename = "CHE")]
    pub che: Option<String>,
    #[serde(rename = "CB")]
    pub cb: Option<String>,
    #[serde(rename = "DAY")]
    pub day: Option<String>,
    #[serde(rename = "DD")]
    pub dd: Option<String>,
    #[serde(rename = "DER")]
    pub der: Option<String>,
    #[serde(rename = "DT")]
    pub dt: Option<String>,
    #[serde(rename = "DIS")]
    pub dis: Option<String>,
    #[serde(rename = "EQA")]
    pub eqa: Option<String>,
    #[serde(rename = "EQF")]
    pub eqf: Option<String>,
    #[serde(rename = "EQP")]
    pub eqp: Option<String>,
    #[serde(rename = "EQR")]
    pub eqr: Option<String>,
    #[serde(rename = "EQT")]
    pub eqt: Option<String>,
    #[serde(rename = "EQI")]
    pub eqi: Option<String>,
    #[serde(rename = "EQS")]
    pub eqs: Option<String>,
    #[serde(rename = "ERA")]
    pub era: Option<String>,
    #[serde(rename = "FAU")]
    pub fau: Option<String>,
    #[serde(rename = "FLE")]
    pub fle: Option<String>,
    #[serde(rename = "FL")]
    pub fl: Option<String>,
    #[serde(rename = "GI")]
    pub gi: Option<String>,
    #[serde(rename = "IZ")]
    pub iz: Option<String>,
    #[serde(rename = "LI")]
    pub li: Option<String>,
    #[serde(rename = "LT")]
    pub lt: Option<String>,
    #[serde(rename = "LY")]
    pub ly: Option<String>,
    #[serde(rename = "MA")]
    pub ma: Option<String>,
    #[serde(rename = "MAU")]
    pub mau: Option<String>,
    #[serde(rename = "MIN")]
    pub min: Option<String>,
    #[serde(rename = "NI")]
    pub ni: Option<String>,
    #[serde(rename = "NUR")]
    pub nur: Option<String>,
    #[serde(rename = "OCT")]
    pub oct: Option<String>,
    #[serde(rename = "PAR")]
    pub par: Option<String>,
    #[serde(rename = "PCE")]
    pub pce: Option<String>,
    #[serde(rename = "PI")]
    pub pi: Option<String>,
    #[serde(rename = "PLU")]
    pub plu: Option<String>,
    #[serde(rename = "PM")]
    pub pm: Option<String>,
    #[serde(rename = "PP")]
    pub pp: Option<String>,
    #[serde(rename = "QC")]
    pub qc: Option<String>,
    #[serde(rename = "RAR")]
    pub rar: Option<String>,
    #[serde(rename = "RD")]
    pub rd: Option<String>,
    #[serde(rename = "RLU")]
    pub rlu: Option<String>,
    #[serde(rename = "S1L")]
    pub s1_l: Option<String>,
    #[serde(rename = "SCO")]
    pub sco: Option<String>,
    #[serde(rename = "SHI")]
    pub shi: Option<String>,
    #[serde(rename = "SIL")]
    pub sil: Option<String>,
    #[serde(rename = "SON")]
    pub son: Option<String>,
    #[serde(rename = "SP")]
    pub sp: Option<String>,
    #[serde(rename = "SPI")]
    pub spi: Option<String>,
    #[serde(rename = "SS")]
    pub ss: Option<String>,
    #[serde(rename = "STA")]
    pub sta: Option<String>,
    #[serde(rename = "STL")]
    pub stl: Option<String>,
    #[serde(rename = "SUN")]
    pub sun: Option<String>,
    #[serde(rename = "SUS")]
    pub sus: Option<String>,
    #[serde(rename = "SWB")]
    pub swb: Option<String>,
    #[serde(rename = "TFA")]
    pub tfa: Option<String>,
    #[serde(rename = "TFO")]
    pub tfo: Option<String>,
    #[serde(rename = "TFP")]
    pub tfp: Option<String>,
    #[serde(rename = "TFS")]
    pub tfs: Option<String>,
    #[serde(rename = "TFT")]
    pub tft: Option<String>,
    #[serde(rename = "TFV")]
    pub tfv: Option<String>,
    #[serde(rename = "TP")]
    pub tp: Option<String>,
    #[serde(rename = "TS")]
    pub ts: Option<String>,
    #[serde(rename = "TWI")]
    pub twi: Option<String>,
    #[serde(rename = "TX")]
    pub tx: Option<String>,
    #[serde(rename = "VS")]
    pub vs: Option<String>,
    #[serde(rename = "ZE")]
    pub ze: Option<String>,
}
